// Auto-generated. Do not edit.
// Sources: Tom_Systema_Floyd/Summer-2026-rosters/week1.csv ... week12.csv
var WEEKLY_DATA = [
  {
    "weekIndex": 1,
    "label": "June 1-5",
    "rows": [
      {
        "studentName": "Akasha Smith",
        "age": "8",
        "group": "Upper",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "Celis Special ($15/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "thereginasmith@gmail.com",
        "additionalNotes": "Melt Belt grilled cheese, Deep River chips, Smooth Moves smoothie",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Campbell Rathlev",
        "age": "5",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lrathlev@gmail.com",
        "additionalNotes": "Already has shirts; no shirt charge",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Georgie Wright",
        "age": "2",
        "group": "Mini",
        "duration": "2 Days",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "Upper",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Lotan Topor",
        "age": "5",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Paul McIntosh",
        "age": "4",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lpratka@pm.me",
        "additionalNotes": "Gluten/dairy/sugar allergy; allergy to hand sanitizer",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Tevet Topor",
        "age": "8",
        "group": "Upper",
        "duration": "Full Week",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Theo Wright",
        "age": "4",
        "group": "Lower",
        "duration": "2 Days",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Vladimir Aheyev",
        "age": "9",
        "group": "Upper",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Small",
        "email": "mperla0605@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Wheeler Wilson",
        "age": "3",
        "group": "Lower",
        "duration": "2 Days",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "zaneywilson@aol.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 1-5"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5",
        "group": "Lower",
        "duration": "Full Week",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 1-5"
      }
    ]
  },
  {
    "weekIndex": 2,
    "label": "June 8-12",
    "rows": [
      {
        "studentName": "Lyla Falzone",
        "age": "6.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut, sesame seed, and green pea allergy; EpiPens required",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Campbell Rathlev",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lrathlev@gmail.com",
        "additionalNotes": "Already has shirts; no shirt charge",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Marsano Spinelli",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "TAYLOR.MATERIO@GMAIL.COM",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Austin Shue",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "agarver2@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Paul McIntosh",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lpratka@pm.me",
        "additionalNotes": "Gluten/dairy/sugar allergy; allergy to hand sanitizer; potty trained",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Matias McCollum",
        "age": "6.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "mparloc0505@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Vladimir Aheyev",
        "age": "9.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "Apple allergy; gluten intolerance",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Lotan Topor",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "Week 2 attending June 8/9/10 only",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Iyar Topor",
        "age": "2.5",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "Only attending June 8/9/10",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Hawthorn Fennell",
        "age": "9.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Medium",
        "email": "fennelljason42@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Hope Jean-Francois",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "daphne&Jean_francois@gmail.com",
        "additionalNotes": "Scholarship inquiry; Mark follow-up",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Cort Pond",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "brittanypond@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Colton Hendrix",
        "age": "10.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jhendrix75@icloud.com",
        "additionalNotes": "Celis: grilled cheese, chips, Very Berry smoothie",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Wiley Lakow",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "sandra.lakow@gmail.com",
        "additionalNotes": "Wiley has big feelings; loved spring break camp support",
        "weekLabel": "June 8-12"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "June 8-12"
      }
    ]
  },
  {
    "weekIndex": 3,
    "label": "June 15-19",
    "rows": [
      {
        "studentName": "Akasha Smith",
        "age": "8.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Special ($15/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "thereginasmith@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Benjamin Mosst",
        "age": "8.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jennifermosst@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Campbell Rathlev",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lrathlev@gmail.com",
        "additionalNotes": "Already has shirts; no shirt charge",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Ellie Bennett",
        "age": "3.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "savannahhuizenga@icloud.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Harrison Galligan",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "virginia.elizabeth.grace@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Hawthorn Fennell",
        "age": "9.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Medium",
        "email": "fennelljason42@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Iyar Topor",
        "age": "2.5",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "Only attending June 8/9/10",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "JJ Molinari",
        "age": "3.5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Monday-Thursday only",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Jayden Vititoe",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "LJ Howe",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Lotan Topor",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Lyla Falzone",
        "age": "6.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy; gluten intolerance",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Tevet Topor",
        "age": "8.0",
        "group": "",
        "duration": "",
        "breakfast": "With fruit daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "kedem.shinar@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Vincent Molinari",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Vladimir Aheyev",
        "age": "9.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Small",
        "email": "mperla0605@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Wells Corbat",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "epompea@gmail.com",
        "additionalNotes": "Tuesday-Thursday only",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Theo Wright",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Georgie Wright",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Madelyn Rogers",
        "age": "6.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Wheeler Wilson",
        "age": "3.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "zaneywilson@aol.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 15-19"
      },
      {
        "studentName": "Taavi Horn",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "phoebehorn87@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 15-19"
      }
    ]
  },
  {
    "weekIndex": 4,
    "label": "June 22-26",
    "rows": [
      {
        "studentName": "Jayden Vititoe",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "JJ Molinari",
        "age": "3.5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Monday-Thursday only",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "LJ Howe",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Graham Olowin",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy; gluten intolerance",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Hudson Horta",
        "age": "6.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "kellyhorta@aol.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Vincent Molinari",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Jayden Vititoe",
        "age": "5.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Theo Wright",
        "age": "4.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 22-26"
      },
      {
        "studentName": "Georgie Wright",
        "age": "2.0",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "lmw340@gmail.com",
        "additionalNotes": "Only attending June 15-16",
        "weekLabel": "June 22-26"
      }
    ]
  },
  {
    "weekIndex": 5,
    "label": "June 29-July 3",
    "rows": [
      {
        "studentName": "Nelson Gonzalez",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy, gluten intolerance",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Sloane Deady-Laakso",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "edeady5180@att.net",
        "additionalNotes": "One day only on June 30",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Matias McCollum",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jerlmccollum@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Hawthorn Fennell",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Medium",
        "email": "fennelljason42@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Tripp Hall",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "shall@sourceonespares.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Graham Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Austin Shue",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "agarver2@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Vincent Molinari",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Remy Sned",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "nikisned@gmail.com",
        "additionalNotes": "Only attending June 29",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "June 29-July 3"
      },
      {
        "studentName": "Teddy Grace",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyannvitko@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "June 29-July 3"
      }
    ]
  },
  {
    "weekIndex": 6,
    "label": "July 6-10",
    "rows": [
      {
        "studentName": "Lilly Heyes",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "Breakfast Daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "priscilla-ten@hotmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Sebastian Martinat",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "danelamartinat@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy, gluten intolerance",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Matias McCollum",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jerlmccollum@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Hawthorn Fennell",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Medium",
        "email": "fennelljason42@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Olive White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Ozzie White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Owen Grant",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Extra Small",
        "email": "ggrant0508@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Vincent Vallier",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "mollyvallier@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Austin Shue",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "agarver2@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Graham Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Jayden Vititoe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Vincent Molinari",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "July 6-10"
      },
      {
        "studentName": "Wheeler Wilson",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "zaneywilson@aol.com",
        "additionalNotes": "",
        "weekLabel": "July 6-10"
      }
    ]
  },
  {
    "weekIndex": 7,
    "label": "July 13-17",
    "rows": [
      {
        "studentName": "Lilly Heyes",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "Breakfast Daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "priscilla-ten@hotmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Theo Trochet",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "susan.trochez@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Ainslee Sheridan",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "Breakfast Daily",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "susan.trochez@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy, gluten intolerance",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Beckham Fox",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "briafoca@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Olive White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "5-day week",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Ozzie White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "5-day week",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Owen Grant",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Extra Small",
        "email": "ggrant0508@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Graham Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Jayden Vititoe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Taavi Horn",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "phoebehorn87@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Wheeler Wilson",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "zaneywilson@aol.com",
        "additionalNotes": "",
        "weekLabel": "July 13-17"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "July 13-17"
      }
    ]
  },
  {
    "weekIndex": 8,
    "label": "July 20-24",
    "rows": [
      {
        "studentName": "Lilly Heyes",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "Breakfast Daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "priscilla-ten@hotmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Ira Skaletsky",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "iamsam1018@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Teddy Thomason",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Medium",
        "email": "olivia.b.thomason@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Griffin McCauley",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "laurenjhooks@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Avery McCauley",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "laurenjhooks@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Nelson Gonzalez",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "1nemayynyr@gmail.com",
        "additionalNotes": "Apple allergy, gluten intolerance",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Beckham Fox",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "brilafoca@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Olive White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Ozzie White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "James 'Duncan' Zahringer III",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "ashleezahringer@gmail.com",
        "additionalNotes": "Interested in Celis option",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Isaiah Plummer",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "mplummer@gunster.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Vincent Vallier",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "mollyvallier@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Graham Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Vincent Molinari",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "l.molinari5588@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Wheeler Wilson",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "zaneywilson@aol.com",
        "additionalNotes": "",
        "weekLabel": "July 20-24"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "July 20-24"
      }
    ]
  },
  {
    "weekIndex": 9,
    "label": "July 27-31",
    "rows": [
      {
        "studentName": "Lilly Heyes",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "Breakfast Daily",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "priscilla-ten@hotmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Ira Skaletsky",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "iamsam1018@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Truett Rogers",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "Sibling: Madelyn Rogers",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Madelyn Rogers",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "Sibling: Truett Rogers",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Matias McCollum",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jerlmccollum@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Olive White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Ozzie White",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kellyklainewhite@gmail.com",
        "additionalNotes": "4-day week",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Vincent Vallier",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "mollyvallier@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Jacob Perna",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "jinglejudi@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Dawson Denney",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "tdenney138@me.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Jayden Vititoe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "sherylmendez22@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Ryder Tarantino",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "ryan.t76@icloud.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Taavi Horn",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "phoebehorn87@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "Upper Campus requested",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Annabelle Dockus",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "jessica.dockus@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Akasha Smith",
        "age": "8",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Special ($15/day)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "thereginasmith@gmail.com",
        "additionalNotes": "",
        "weekLabel": "July 27-31"
      },
      {
        "studentName": "Wiley Lakow",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "sandra.lakow@gmail.com",
        "additionalNotes": "Wiley has big feelings",
        "weekLabel": "July 27-31"
      }
    ]
  },
  {
    "weekIndex": 10,
    "label": "Aug 3-7",
    "rows": [
      {
        "studentName": "Graham Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Grant 'Geo' Olowin",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "Twin",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Carter Grant",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Small",
        "email": "ggrant0508@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Owen Grant",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Weekly",
        "shirtSize": "Extra Small",
        "email": "ggrant0508@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "LJ Howe",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Small",
        "email": "howewedding17@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Matias McCollum",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jerlmccollum@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Charlotte Eady",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "ashleyeady@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Liam Eady",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "ashleyeady@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Henry Reynolds",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Wells Corbat",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "epompea@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Jack Morrison",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Lydia Gioia",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Alex Gioia",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Luka DeAraujo",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "till.amanda@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Aria Falzone",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "marilyn@thefalzones.net",
        "additionalNotes": "Peanut/sesame/green pea allergy",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Collyn",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Hunter",
        "age": "",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Ballapiatt Ryan",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "ballapiatt25@hotmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Scott Wilder",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      },
      {
        "studentName": "Lakow Wiley",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "sandra.lakow@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 3-7"
      }
    ]
  },
  {
    "weekIndex": 11,
    "label": "Aug 10-14",
    "rows": [
      {
        "studentName": "Truett Rogers",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "Sibling: Madelyn Rogers",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Madelyn Rogers",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "Sibling: Truett Rogers",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Tilly Robinson",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jvrobinson@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Cosmo Robinson",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "jvrobinson@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Maciej Kozakowski",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "jvrobinson@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Julia Kozakowska",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "jvrobinson@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Marlow Rollins",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "kristh.h.rollins@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Sloane Deady-Laakso",
        "age": "7",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "edeady5180@att.net",
        "additionalNotes": "4-day week only",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "Aug 10-14"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 10-14"
      }
    ]
  },
  {
    "weekIndex": 12,
    "label": "Aug 17-21",
    "rows": [
      {
        "studentName": "Madelyn Rogers",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "Sibling: Truett Rogers",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Marlow Rollins",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Celis Lunch",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "kristh.h.rollins@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Lily Johnson",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "chanemurphy@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "August Johnson",
        "age": "2",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "",
        "email": "chanemurphy@gmail.com",
        "additionalNotes": "Potty trained",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Remy Zimmer",
        "age": "6",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "ericapaigezimmer@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Zoey Zimmer",
        "age": "8",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "ericapaigezimmer@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Reagan Olowin",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Medium",
        "email": "amandaolowin@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Wyld Torrealba",
        "age": "3",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "",
        "email": "laurenmusselman84@gmail.com",
        "additionalNotes": "Vegan family",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Herbst Capri",
        "age": "10",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Large",
        "email": "bg03interiors@aol.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Hawthorn Fennell",
        "age": "9",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "Aftercare Daily",
        "shirtSize": "Medium",
        "email": "fennelljason42@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Leo Hamric",
        "age": "5",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($7.75/day)",
        "beforeAfterCare": "Aftercare ($25/day)",
        "shirtSize": "Extra Small",
        "email": "email.mlafuente@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Truett Rogers",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "None",
        "beforeAfterCare": "None",
        "shirtSize": "Extra Small",
        "email": "jgwenberry@yahoo.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      },
      {
        "studentName": "Wilder Scott",
        "age": "4",
        "group": "",
        "duration": "",
        "breakfast": "None",
        "lunch": "Pizza ($30/week)",
        "beforeAfterCare": "None",
        "shirtSize": "Small",
        "email": "farrahkscott@gmail.com",
        "additionalNotes": "",
        "weekLabel": "Aug 17-21"
      }
    ]
  }
];
